<script type="text/javascript">
<!-- 
document.writeln(" #!/bin/bash "); 
document.writeln(" # Rai.TV download script "); 
document.writeln(" # Created by Daniil Gentili (http://daniil.it) "); 
document.writeln(" # This program is licensed under the GPLv3 license. "); 
document.writeln("  "); 
document.writeln("  "); 
document.writeln(" #################################################### "); 
document.writeln(" ############# Beginning of the script ############## "); 
document.writeln(" #################################################### "); 
document.writeln("  "); 
document.writeln(" [ \"$*\" = \"\" ] && exit 1 "); 
document.writeln(" [ \"$1\" = \"\" ] && exit 1 "); 
document.writeln(" [ \"$1\" = \"dontmindme\" ] && exit 1 "); 
document.writeln("  "); 
document.writeln("  "); 
document.writeln("  "); 
document.writeln(" api() { "); 
document.writeln("  ####################################################  "); 
document.writeln("  ####### Beginning of URL recognition section ####### "); 
document.writeln("  #################################################### "); 
document.writeln("   "); 
document.writeln("  dl=\"$(echo \"$1\" | grep -q '^//' && echo \"http:$1\" || echo \"$1\")\" "); 
document.writeln("   "); 
document.writeln("  urltype=\"$(curl -w \"%{url_effective}\n\" -L -s -I -S \"$dl\" -o /dev/null | sed 's/^HTTP:\/\//http:\/\//g')\" "); 
document.writeln("   "); 
document.writeln("   "); 
document.writeln("  echo \"$urltype\" | grep -qE '.*rai.it/.*|.*rai.tv/.*|.*rainews.it/.*'  && ptype=rai "); 
document.writeln(" # grep -qE 'http://www.*.rai..*/dl/RaiTV/programmi/media/.*|http://www.*.rai..*/dl/RaiTV/tematiche/.*|http://www.*.rai..*/ dl/.*PublishingBlock-.*|http://www.*.rai..*/dl/replaytv/replaytv.html.*|http://.*.rai.it/.*|http://www.rainews.it/dl/rainews/.*|https://www.*.rai..*/dl/ RaiTV/programmi/media/.*|https://www.*.rai..*/dl/RaiTV/tematiche/.*|https://www.*.rai..*/dl/.*PublishingBlock-.*|https://www.*.rai..*/dl/ replaytv/replaytv.html.*|https://.*.rai.it/.*|https://www.rainews.it/dl/rainews/.*' && ptype=rai "); 
document.writeln("   "); 
document.writeln("   "); 
document.writeln("  echo \"$urltype\" | grep -qE '.*mediaset.it/.*|http://www.video.mediaset.it/player/playerIFrame.*|https://www.video.mediaset.it/video/.*|https://www.video.mediaset.it/player/playerIFrame.*|tgcom24.mediaset.it/video/.*|http://mediaset.it/.*|https://mediaset.it/.*' && ptype=mediaset "); 
document.writeln("   "); 
document.writeln("  echo \"$urltype\" | grep -qE 'http://.*wittytv.it/.*|https://.*wittytv.it/.*' && ptype=mediaset && witty=y "); 
document.writeln("   "); 
document.writeln("  echo \"$urltype\" | grep -qE 'http://la7.it/.*|http://.*.la7.it/.*|http://la7.tv/.*|http://.*.la7.tv/.*|https://la7.it/.*|https://.*.la7.it/.*|https://la7.tv/.*| https://.*.la7.tv/.*' && ptype=lasette "); 
document.writeln("   "); 
document.writeln("  echo \"$urltype\" | grep -qE '.*dplay.com/.*|.*dmax.it.*|.*realtimetv.it.*|.*giallotv.it.*|.*focustv.it.*|.*k2tv.it.*|.*frisbeetv.it.*' && ptype=dplay "); 
document.writeln("   "); 
document.writeln("  echo \"$urltype\" | grep -qE '.*deejay.it.*' && ptype=deejay "); 
document.writeln("   "); 
document.writeln("  echo \"$urltype\" | grep -qE '.*eurosport.com.*' && ptype=eurosport "); 
document.writeln("  echo \"$urltype\" | grep -qE '.*wat.tv.*' && ptype=wat "); 
document.writeln("   "); 
document.writeln("  [ \"$ptype\" = \"\" ] && ptype=\"common\" "); 
document.writeln("   "); 
document.writeln("  dl=\"$urltype\" "); 
document.writeln("  [ \"$ptype\" = \"rai\" ] && echo \"$1\" | grep -q '#' && dl=\"$1\" "); 
document.writeln("   "); 
document.writeln("  ############################################################################## "); 
document.writeln("  ####### End of URL recognition section, beginning of Functions section ####### "); 
document.writeln("  ############################################################################## "); 
document.writeln("  "); 
document.writeln("  # Declare javascript variable "); 
document.writeln("  "); 
document.writeln("  var() { "); 
document.writeln("   eval $(echo \"$*\" | sed 's/var//g;s/\s=\s/=/g') "); 
document.writeln("  } "); 
document.writeln("  # Get video information "); 
document.writeln("  "); 
document.writeln("  getsize() { "); 
document.writeln("   minfo=\"$(timeout -skill 10s mediainfo \"$a\")\" "); 
document.writeln("   d=$(echo \"$a\" | sed \"s/.*\.//;s/[^a-z|0-9].*//\") "); 
document.writeln("   b=$(echo \"$minfo\" | sed '/File size/!d;s/.*:\s//g') "); 
document.writeln("   c=$(echo \"$minfo\" | sed '/Width\|Height/!d;s/.*:\s//g;s/\spixels//g;s/\s//g;/^\s*$/d' | tr -s \"\n\" x | sed 's/x$//g') "); 
document.writeln("   [ \"$b\" = \"\" ] && b=\"Unkown size\" "); 
document.writeln("   [ \"$c\" = \"\" ] && c=\"Unkown quality\" "); 
document.writeln("   info=\"($d, $b, $c)\" "); 
document.writeln(" #sed 's/\ "); 
document.writeln(" #//g;s/^, //g;s/, B,/, Unkown size,/g;s/, ,/,/g;s/^B,//g;s/, $//;s/ $//g'))\" "); 
document.writeln("   minfo= "); 
document.writeln("  } "); 
document.writeln("  "); 
document.writeln("  "); 
document.writeln("  # Check if URL exists and remove copies of the same URL "); 
document.writeln("  "); 
document.writeln("  checkurl() { "); 
document.writeln("  tbase=\"$(echo \"$base\" | sed 's/ /%20/g;s/%20http:\/\//\ "); 
document.writeln(" http:\/\//g;s/%20https:\/\//\ "); 
document.writeln(" https:\/\//g;s/%20$//g;s/ /\ "); 
document.writeln(" /g' | awk '!x[$0]++')\" "); 
document.writeln("  "); 
document.writeln("  base= "); 
document.writeln("  for u in $tbase;do echo \"$u\" | grep -q 'rmtp://\|mms://' && { "); 
document.writeln("   base=\"$base "); 
document.writeln(" $u\" "); 
document.writeln("   } || { "); 
document.writeln("   wget -S --tries=3 --spider \"$u\" 2>&1 | grep -q '200 OK\|206 Partial' && base=\"$base "); 
document.writeln(" $u\" "); 
document.writeln("   }; done "); 
document.writeln("  } "); 
document.writeln("  "); 
document.writeln("  "); 
document.writeln("  # Nicely format input "); 
document.writeln("  "); 
document.writeln("  formatoutput() { "); 
document.writeln("  "); 
document.writeln("   case $ptype in "); 
document.writeln("    rai) "); 
document.writeln("     two=\"$(echo \"$unformatted\" | grep '.*_250.mp4')\" "); 
document.writeln("     four=\"$(echo \"$unformatted\" | grep '.*_400.mp4')\" "); 
document.writeln("     six=\"$(echo \"$unformatted\" | grep '.*_600.mp4')\" "); 
document.writeln("     seven=\"$(echo \"$unformatted\" | grep '.*_700.mp4')\" "); 
document.writeln("     eight=\"$(echo \"$unformatted\" | grep '.*_800.mp4')\" "); 
document.writeln("     twelve=\"$(echo \"$unformatted\" | grep '.*_1200.mp4')\" "); 
document.writeln("     fifteen=\"$(echo \"$unformatted\" | grep '.*_1500.mp4')\" "); 
document.writeln("     eighteen=\"$(echo \"$unformatted\" | grep '.*_1800.mp4')\" "); 
document.writeln("     twentyfour=\"$(echo \"$unformatted\" | grep '.*_2400.mp4')\" "); 
document.writeln("     thirtytwo=\"$(echo \"$unformatted\" | grep '.*_3200.mp4')\" "); 
document.writeln("     fourthousand=\"$(echo \"$unformatted\" | grep '.*_4000.mp4')\" "); 
document.writeln("     normal=\"$(echo \"$unformatted\" | sed '/.*_250\.mp4/d;/.*_400\.mp4/d;/.*_600\.mp4/d;/.*_700\.mp4/d;/.*_800\.mp4/d;/.*_1200\.mp4/d;/.*_1500\.mp4/d;/.*_1800\.mp4/d;/.*_2400\.mp4/d;/.*_3200\.mp4/d;/.*_4000\.mp4/d')\" "); 
document.writeln("     ;; "); 
document.writeln("    mediaset) "); 
document.writeln("     mp4=\"$(echo \"$unformatted\" | grep \".mp4\")\" "); 
document.writeln("     smooth=\"$(echo \"$unformatted\" | sed '/pl[)]/d;/est/!d')\" "); 
document.writeln("     apple=\"$(echo \"$unformatted\" | grep \"pl)\")\" "); 
document.writeln("     wmv=\"$(echo \"$unformatted\" | grep \".wmv\")\" "); 
document.writeln("     flv=\"$(echo \"$unformatted\" | grep \".flv\")\" "); 
document.writeln("     f4v=\"$(echo \"$unformatted\" | grep \".f4v\")\" "); 
document.writeln("     ;; "); 
document.writeln("    lasette) "); 
document.writeln("     lamp4=\"$(echo \"$unformatted\" | sed '/master/d;/manifest/d;/\.mp4/!d')\" "); 
document.writeln("     ;; "); 
document.writeln("    *) "); 
document.writeln("     common=\"$unformatted\" "); 
document.writeln("   esac "); 
document.writeln("  "); 
document.writeln("  "); 
document.writeln("   formats=\"$( "); 
document.writeln(" [ \"$common\" != \"\" ] && for a in $common; do getsize "); 
document.writeln(" # info=\"$(echo \"$info\" | sed 's/[(]//;s/[)]//')\" "); 
document.writeln("  echo \"$info $a\";done "); 
document.writeln(" [ \"$lamp4\" != \"\" ] && for a in $lamp4; do getsize "); 
document.writeln("  echo \"$info $a\";done "); 
document.writeln(" [ \"$normal\" != \"\" ] && for a in $normal; do getsize "); 
document.writeln("  echo \"$info $a\";done "); 
document.writeln(" [ \"$fourthousand\" != \"\" ] && for a in $fourthousand; do getsize "); 
document.writeln("  echo \"Full HD quality $info $a\";done "); 
document.writeln(" [ \"$thirtytwo\" != \"\" ] && for a in $thirtytwo; do getsize "); 
document.writeln("  echo \"HD quality $info $a\";done "); 
document.writeln(" [ \"$twentyfour\" != \"\" ] && for a in $twentyfour; do getsize "); 
document.writeln("  echo \"Super-high quality $info $a\";done "); 
document.writeln(" [ \"$eighteen\" != \"\" ] && for a in $eighteen; do getsize "); 
document.writeln("  echo \"High quality $info $a\";done "); 
document.writeln(" [ \"$fifteen\" != \"\" ] && for a in $fifteen; do getsize "); 
document.writeln("  echo \"Medium-high quality $info $a\";done "); 
document.writeln(" [ \"$twelve\" != \"\" ] && for a in $twelve; do getsize "); 
document.writeln("  echo \"Medium quality $info $a\";done "); 
document.writeln(" [ \"$seven\" != \"\" ] && for a in $seven; do getsize "); 
document.writeln("  echo \"Medium-medium quality $info $a\";done "); 
document.writeln(" [ \"$eight\" != \"\" ] && for a in $eight; do getsize "); 
document.writeln("  echo \"Medium-low quality $info $a\";done "); 
document.writeln("   "); 
document.writeln(" [ \"$six\" != \"\" ] && for a in $six; do getsize "); 
document.writeln("   "); 
document.writeln("  echo \"Low quality $info $a\";done "); 
document.writeln(" [ \"$four\" != \"\" ] && for a in $four; do getsize "); 
document.writeln("  echo \"Minimum quality $info $a\";done "); 
document.writeln("   "); 
document.writeln(" [ \"$two\" != \"\" ] && for a in $two; do getsize "); 
document.writeln("  echo \"Lowest Minimum quality $info $a\";done "); 
document.writeln(" [ \"$mp4\" != \"\" ] && for a in $mp4; do getsize "); 
document.writeln("  echo \"Medium-high quality $info $a\";done "); 
document.writeln(" [ \"$wmv\" != \"\" ] && for a in $wmv; do getsize "); 
document.writeln("  echo \"Low quality $info $a\";done "); 
document.writeln(" [ \"$flv\" != \"\" ] && for a in $flv; do getsize "); 
document.writeln("  echo \"Low quality $info $a\";done "); 
document.writeln(" [ \"$f4v\" != \"\" ] && for a in $f4v; do getsize "); 
document.writeln("  echo \"Low quality $info $a\";done "); 
document.writeln(" [ \"$smooth\" != \"\" ] && for a in $smooth; do echo \"High quality (smooth streaming, smooth) $a\";done "); 
document.writeln(" [ \"$apple\" != \"\" ] && for a in $apple; do echo \"Medium-low quality  (apple streaming, pseudo-m3u8, m3u8) $a\";done "); 
document.writeln(" )\" "); 
document.writeln("   "); 
document.writeln("   formats=\"$(echo \"$formats\" | awk '!x[$0]++' | awk '{print $(NF-1), $0}' | sort -gr | cut -d' ' -f2- | sed '/^\s*$/d')\" "); 
document.writeln("   videoTitolo=$(echo \"$videoTitolo\" | tr -d '\015' | tr -s \"\n\" \" \") "); 
document.writeln("   title=\"${videoTitolo//[^a-zA-Z0-9 ]/}\" "); 
document.writeln("   title=$(echo $title | sed 's/^\s*//g;s/\s*$//g') "); 
document.writeln("   title=${title// /_} "); 
document.writeln("  } "); 
document.writeln("  "); 
document.writeln("  "); 
document.writeln("  ###########################################################################################  "); 
document.writeln("  ################## End of formatting section, beginning of Rai section ################## "); 
document.writeln("  ########################################################################################### "); 
document.writeln("  "); 
document.writeln("  "); 
document.writeln("  rai() {  "); 
document.writeln("   saferai=\"$1\" "); 
document.writeln("   # Store the page in a variable "); 
document.writeln("   file=$(wget \"$saferai\" -q -O -) "); 
document.writeln("  "); 
document.writeln("   # Rai replay or normal rai website choice "); 
document.writeln("   echo \"$1\" | grep -q 'http://www.*.rai..*/dl/replaytv/replaytv.html.*' && replay \"$saferai\" || rai_normal \"$saferai\" "); 
document.writeln("   links=\"$videoURL_M3U8 $videoURL_MP4 $videoURL_H264 $videoURL_WMV $videoURL $replay\" "); 
document.writeln("   links=\"$(echo \"$links\" | sed '/^\s*$/d')\" "); 
document.writeln("   videoTitolo=\"$(echo -en \"$videoTitolo\")\" "); 
document.writeln("   [ \"$links\" = \"\" ] && replay \"$saferai\" "); 
document.writeln("   links=\"$videoURL_M3U8 $videoURL_MP4 $videoURL_H264 $videoURL_WMV $videoURL $replay\" "); 
document.writeln("   [ \"$videoTitolo\" = \"\" ] && videoTitolo=$(echo \"$file\" | tr '\n' ' ' | sed 's/.*<title>//;s/<\/title>.*//;s/^ //') "); 
document.writeln("   # Resolve relinkers "); 
document.writeln("   relinker_rai \"$links\" "); 
document.writeln("  } "); 
document.writeln("  "); 
document.writeln("  "); 
document.writeln("  # Rai website  "); 
document.writeln("  "); 
document.writeln("  rai_normal() { "); 
document.writeln("  "); 
document.writeln("   echo \"$1\" | grep -q \"rainews.it\" && { "); 
document.writeln("    bsp=$(echo \"$file\" | sed '/parentPage.bsp /!d;'\"s/.* '//;s/'.*//\") "); 
document.writeln("    jsons=$(echo \"$file\" | sed '/\"url\" : \"http/!d;s/.* : \"//;s/\".*//') "); 
document.writeln("    json=$(curl -s $jsons) "); 
document.writeln("   } || { "); 
document.writeln("    # iframe check "); 
document.writeln("    echo \"$file\" | grep -q videoURL || { urls=\"http://www.rai.it/dl/RaiTV/programmi/media/\"$(echo \"$file\" | sed '/content=\"ContentItem/!d;s/.*content=\"//g;s/\".*//g')\".html http://www.rai.tv$(echo \"$file\" | grep -A1 '<div id=\"idFramePlayer\">' | sed '/\<iframe/!d;s/.*src=\"//g;s/?.*//g') $(echo \"$file\" | sed '/drawMediaRaiTV/!d;s/.*http/http/g;s/'\"'\"'.*//g')\"; file=\"$(wget -qO- $urls)\"; } "); 
document.writeln("   } "); 
document.writeln("   # read and declare videoURL and videoTitolo variables from javascript in page "); 
document.writeln("  "); 
document.writeln("   $(echo \"$file\" | grep 'videoTitolo\|videoURL') "); 
document.writeln("  "); 
document.writeln("  } "); 
document.writeln("  "); 
document.writeln("  "); 
document.writeln("  # Rai replay function "); 
document.writeln("  "); 
document.writeln("  replay() { "); 
document.writeln("   # Get the video id "); 
document.writeln("   v=$(echo \"$1\" | sed 's/.*v=//;s/\&.*//') "); 
document.writeln("  "); 
document.writeln("   # Get the day "); 
document.writeln("   day=$(echo \"$1\" | sed 's/.*day=//;s/\&.*//;s/-/_/g;/http/d') "); 
document.writeln("   [ \"$day\" = \"\" ] && day=$(echo \"$1\" | sed 's/.*vd=//;s/\&.*//;s/-/_/g') "); 
document.writeln("  "); 
document.writeln("   ch=$(echo \"$1\" | sed 's/.*ch=//;s/\&.*//;/http/d') "); 
document.writeln("   [ \"$ch\" = \"\" ] && ch=$(echo \"$1\" | sed 's/.*vc=//;s/\&.*//') "); 
document.writeln("  "); 
document.writeln("   # Get the channel "); 
document.writeln("   case $ch in "); 
document.writeln("    1) "); 
document.writeln("     ch=RaiUno "); 
document.writeln("     ;; "); 
document.writeln("    2) "); 
document.writeln("     ch=RaiDue "); 
document.writeln("     ;; "); 
document.writeln("    3) "); 
document.writeln("     ch=RaiTre "); 
document.writeln("     ;; "); 
document.writeln("    31) "); 
document.writeln("     ch=RaiCinque "); 
document.writeln("     ;; "); 
document.writeln("    32) "); 
document.writeln("     ch=RaiPremium "); 
document.writeln("     ;; "); 
document.writeln("    23) "); 
document.writeln("     ch=RaiGulp "); 
document.writeln("     ;; "); 
document.writeln("    38) "); 
document.writeln("     ch=RaiYoyo "); 
document.writeln("     ;; "); 
document.writeln("   esac "); 
document.writeln("  "); 
document.writeln("   # Get the json "); 
document.writeln(" tmpjson=\"$(wget http://www.rai.it/dl/portale/html/palinsesti/replaytv/static/\"$ch\"_$day.html -qO- | tr '\n' ' ')\" "); 
document.writeln("  "); 
document.writeln("   # Keep only section with correct video id and make it grepable "); 
document.writeln("   json=\"$(echo \"$tmpjson\" | sed 's/'$v'.*//g;s/.*[{]//g;s/\,/\ "); 
document.writeln(" /g')\" "); 
document.writeln("  "); 
document.writeln("   # Get the relinkers "); 
document.writeln("   replay=$(echo \"$json\" | sed '/mediapolis/!d;s/.*\\"://g;s/\\"//g;s/^ *//g') "); 
document.writeln("  "); 
document.writeln("   # Get the title "); 
document.writeln("   videoTitolo=$(echo \"$json\" | sed '/\\"t\\":/!d;s/.*\\"://;s/\\"//g;s/^ *//g') "); 
document.writeln("  } "); 
document.writeln("  "); 
document.writeln("  "); 
document.writeln("  # Relinker function "); 
document.writeln("  "); 
document.writeln("  "); 
document.writeln("  "); 
document.writeln("  relinker_rai() { "); 
document.writeln("  # Resolve relinker "); 
document.writeln("  "); 
document.writeln("  "); 
document.writeln("   for f in $(echo $* | awk '{ while(++i<=NF) printf (!a[$i]++) ? $i FS : \"\"; i=split(\"\",a); print \"\" }'); do "); 
document.writeln("    dl=$(echo \"$f\" | grep -q '^//' && echo \"http:$f\" || echo \"$f\") "); 
document.writeln("  "); 
document.writeln("  "); 
document.writeln("    base=\"$(curl \"$dl\" | sed 's/ /%20/g')\" && checkurl "); 
document.writeln("    # 1st method "); 
document.writeln("  "); 
document.writeln("    url=\"$(timeout -skill 5s wget -qO- \"$dl&output=25\") "); 
document.writeln("  $(timeout -skill 5s wget \"$dl&output=43\" -U=\"\" -q -O -)\" "); 
document.writeln("  "); 
document.writeln("    url=\"$(echo \"$url\" | sed 's/ /%20/g;s/[>]/\ "); 
document.writeln(" /g;s/[<]/\ "); 
document.writeln(" /g')\" "); 
document.writeln("  "); 
document.writeln("    [ \"$url\" != \"\" ] && base=\"$(echo \"$url\" | sed '/\.mp4\|\.wmv\|\.mov/!d;s/mms/http/g;/http/!d;s/\.mp4.*/\.mp4/;s/\.wmv.*/\.wmv/;s/\.mov.*/\.mov/')\" && checkurl "); 
document.writeln("  "); 
document.writeln("  "); 
document.writeln("    # 2nd method "); 
document.writeln("    [ \"$base\" = \"\" ] && { "); 
document.writeln("     base=$(curl -w \"%{url_effective}\n\" -L -s -I -S \"$dl\" -A \"\" -o /dev/null) && checkurl "); 
document.writeln("    } "); 
document.writeln("  "); 
document.writeln("    [ \"$base\" = \"\" ] && { "); 
document.writeln("     base=\"$(for f in $(echo \"$url\" | grep \",\"); do number=\"$(echo \"$f\" | sed 's/http\:\/\///g;s/\/.*//;s/[^0-9]//g;s/^.*\(.\{1\}\)$/\1/')\"; echo \"$f\" | sed 's/.*Italy/Italy/;s/^/http\:\/\/creativemedia'$number'\.rai\.it\//;s/,/{/;s/,\./}\./;s/\.mp4.*/\.mp4/'; done)\"  "); 
document.writeln("     base=\"$(eval echo \"$base\")\" && checkurl "); 
document.writeln("    } "); 
document.writeln("   "); 
document.writeln("  "); 
document.writeln("    # 3rd and 4th method "); 
document.writeln("    [ \"$base\" = \"\" ] && { "); 
document.writeln("     url=\"$(wget \"$dl&output=4\" -q -O -)\" "); 
document.writeln("     [ \"$url\" != \"\" ] && echo \"$url\" | grep -q 'creativemedia\|wms' && base=\"$url\" && checkurl "); 
document.writeln("    } "); 
document.writeln("  "); 
document.writeln("  "); 
document.writeln("    TMPURLS=\"$TMPURLS "); 
document.writeln(" $base\" "); 
document.writeln("  "); 
document.writeln("   done "); 
document.writeln("  "); 
document.writeln("   # Remove copies of the same url "); 
document.writeln("   base=\"$(echo \"$TMPURLS\" | sort | awk '!x[$0]++')\" "); 
document.writeln("  "); 
document.writeln("   # Find all qualities in every video "); 
document.writeln("   tbase= "); 
document.writeln("   loop=\"_250 _400 _600 _700 _800 _1200 _1500 _1800 _2400 _3200 _4000\" "); 
document.writeln("    "); 
document.writeln("   for t in $loop \ ; do [ \"$t\" = \" \" ] && t=; for i in $loop; do tbase=\"$tbase "); 
document.writeln(" ${base//$t\.mp4/$i\.mp4}\"; tbase=\"$(echo \"$tbase\" | grep -Ev \"_([0-9]{3,4})_([0-9]{3,4})\.mp4\" | awk '!seen[$0]++')\"; done;done "); 
document.writeln("  "); 
document.writeln("  "); 
document.writeln("   base=\"$tbase\" "); 
document.writeln("  "); 
document.writeln("   checkurl "); 
document.writeln("  "); 
document.writeln("   unformatted=\"$base\" "); 
document.writeln("   formatoutput "); 
document.writeln("  } "); 
document.writeln("  "); 
document.writeln("  "); 
document.writeln("  ########################################################################################### "); 
document.writeln("  ##################### End of Rai section, beginning of Lasette section #################### "); 
document.writeln("  ########################################################################################### "); 
document.writeln("  "); 
document.writeln("  "); 
document.writeln("  lasette() { "); 
document.writeln("   # Store the page in a variable "); 
document.writeln("   page=\"$(wget \"$1\" -q -O -)\" "); 
document.writeln("  "); 
document.writeln("   # Get the javascript with the URLs "); 
document.writeln("   unformatted=\"$(wget -q -O - $(echo \"$page\" | sed '/starter/!d;s/.*src\=\\"//;s/\\".*//') | sed '/src:.*\|src_.*/!d;s/.*\: \\"//;s/\\".*//')\" "); 
document.writeln("  "); 
document.writeln("   # Get the title "); 
document.writeln("   videoTitolo=\"$(echo \"$page\" | tr '\n' ' ' | sed 's/.*<title>//;s/<\/title>.*//;s/^ //')\" "); 
document.writeln("  "); 
document.writeln("   formatoutput "); 
document.writeln("  } "); 
document.writeln("  "); 
document.writeln("  "); 
document.writeln("  "); 
document.writeln("  ########################################################################################### "); 
document.writeln("  ################## End of Lasette section, beginning of Mediaset section ################## "); 
document.writeln("  ########################################################################################### "); 
document.writeln("  "); 
document.writeln("  "); 
document.writeln("  "); 
document.writeln("  mediaset() { "); 
document.writeln("   # Store the page in a variable "); 
document.writeln("   page=$(wget \"$1\" -q -O -) "); 
document.writeln("  "); 
document.writeln("   # Witty tv recongition "); 
document.writeln("   [ \"$witty\" = \"y\" ] && { "); 
document.writeln("    # Get the video id "); 
document.writeln("    id=$(echo \"$page\" | sed '/[<]iframe id=\\"playeriframe\\" src=\\"[^\/]*\/\/www.video.mediaset.it\/player\/playerIFrame.shtml?id\=/!d;s/.*\<iframe id=\\"playeriframe\\" src=\\"[^\/]*\/\/www.video.mediaset.it\/player\/playerIFrame.shtml?id\=//;s/\&.*//') "); 
document.writeln("  "); 
document.writeln("    # Get the title "); 
document.writeln("    videoTitolo=$(echo \"$page\" | sed '/[<]meta content=\\".*\\" property=\\".*title\\"\/[>]/!d;s/\\" property=\\".*title\\".*//g;s/.*\<meta content\=\\"//;s/\\".*//g') "); 
document.writeln("  "); 
document.writeln("   } || { "); 
document.writeln("    $(echo \"$page\" | grep \"var videoMetadataId\") "); 
document.writeln("    id=\"$videoMetadataId\" "); 
document.writeln("    videoTitolo=$(echo \"$page\" | sed '/[<]meta content=\\".*\\" property=\\".*title\\"\/[>]/!d;s/\\" property=\\".*title\\".*//g;s/.*\<meta content\=\\"//;s/\\".*//g') "); 
document.writeln("   } "); 
document.writeln("  "); 
document.writeln("   # Get the video URLs using the video id "); 
document.writeln("   unformatted=\"$(wget \"http://cdnselector.xuniplay.fdnames.com/GetCDN.aspx?streamid=$id\" -O - -q -U=\"\" | sed 's/</\ "); 
document.writeln(" /g' | grep http | sed 's/.*http/http/g;s/\\".*//g')\" "); 
document.writeln("  "); 
document.writeln("   formatoutput "); 
document.writeln("  "); 
document.writeln("  } "); 
document.writeln("  "); 
document.writeln("  ########################################################################################### "); 
document.writeln("  ##################### End of Mediaset section, beginning of dplay section ################ "); 
document.writeln("  ########################################################################################### "); 
document.writeln("  "); 
document.writeln("  dplay() { "); 
document.writeln("   id=$(curl -Ls \"$dl\" | sed '/data-video-id\=\\"/!d;s/.*data-video-id\=\\"//g;s/\\".*//g') "); 
document.writeln("   [ \"$id\" = \"\" ] && { "); 
document.writeln("    orig=$(curl -Ls \"$dl\" | sed '/dplay.com/!d;s/.*href=\"http/http/g;s/\".*//g') &&  "); 
document.writeln("    id=$(curl -Ls \"$orig\" | sed '/data-video-id\=\\"/!d;s/.*data-video-id\=\\"//g;s/\\".*//g') "); 
document.writeln("   } "); 
document.writeln("   json=\"$(curl -Ls http://it.dplay.com/api/v2/ajax/videos?video_id=$id)\" "); 
document.writeln("   unformatted=\"$(echo \"$json\" | sed 's/\\"\:\\"/\ "); 
document.writeln(" /g' | sed '/mp4/!d;s/\\".*//g;s/\\//g')\" "); 
document.writeln("   videoTitolo=$(echo \"$json\" | sed 's/.*\",\"title\":\"//g;s/\".*//g') "); 
document.writeln("   formatoutput "); 
document.writeln("  } "); 
document.writeln("  "); 
document.writeln("  ########################################################################################### "); 
document.writeln("  ##################### End of dplay section, beginning of deejay section ################ "); 
document.writeln("  ########################################################################################### "); 
document.writeln("  deejay() { "); 
document.writeln("   file=\"$(curl -sL \"$1\")\" "); 
document.writeln("   unformatted=\"$(echo \"$file\" | sed '/addParam[(]'\"'\"'format'\"'\"', /!d;s/.*'\"'\"'http/http/g;s/'\"'\"'.*//g')\" "); 
document.writeln("   videoTitolo=$(echo $file | sed 's/.*<title>//;s/<\/title>.*//;s/^ //') "); 
document.writeln("   formatoutput "); 
document.writeln("  } "); 
document.writeln("  "); 
document.writeln("  ########################################################################################### "); 
document.writeln("  ##################### End of deejay section, beginning of eurosport section ################ "); 
document.writeln("  ########################################################################################### "); 
document.writeln("  eurosport() { "); 
document.writeln("   file=\"$(curl -sL \"$1\")\" "); 
document.writeln("   frame=\"$(echo $file | sed 's/.*src=\\"http:\/\/www.wat.tv\/embedframe/http:\/\/www.wat.tv\/embedframe/g;s/\\".*//g')\" "); 
document.writeln("   videoTitolo=$(echo $file | sed 's/.*<title>//;s/<\/title>.*//;s/^ //') "); 
document.writeln("   wat_base \"$frame\" "); 
document.writeln("   formatoutput "); 
document.writeln("  } "); 
document.writeln("  ########################################################################################### "); 
document.writeln("  ##################### End of eurosport section, beginning of wat section ################ "); 
document.writeln("  ########################################################################################### "); 
document.writeln("  "); 
document.writeln("  wat_base() { "); 
document.writeln("   file=\"$(curl -sL \"$1\")\" "); 
document.writeln("   unformatted=\"$(echo \"$file\" | sed 's/,/\ "); 
document.writeln(" /g' | sed '/PlayerLite.swf?videoId=/!d;s/.*\/\/www.wat.tv\/images/\/\/wat.tv\/images/g;s/\\".*//g' | awk '!x[$0]++')\" "); 
document.writeln("  "); 
document.writeln("  } "); 
document.writeln("  wat() { "); 
document.writeln("   wat_base \"$1\" "); 
document.writeln("   videoTitolo=$(echo $file | sed 's/.*<title>//;s/<\/title>.*//;s/^ //') "); 
document.writeln("   formatoutput "); 
document.writeln("  } "); 
document.writeln("  ########################################################################################### "); 
document.writeln("  ##################### End of wat section, beginning of common section ################ "); 
document.writeln("  ########################################################################################### "); 
document.writeln("  "); 
document.writeln("  common() { "); 
document.writeln("   # Store the page in a variable "); 
document.writeln("   page=\"$(wget -q -O - \"$1\")\" "); 
document.writeln("  "); 
document.writeln("   json=\"$(youtube-dl -J \"$1\" | ./JSON.sh -s)\" "); 
document.writeln("   videoTitolo=$(echo \"$json\" | sed '/\[\"title\"\]/!d;s/.*\t\"//g;s/\".*//g') "); 
document.writeln("   urls=\"$(echo \"$json\" | sed '/\[\"formats\",.*,\"url\"\]\|\[\"url\"\]\|\[\"entries\",.*,\"url\"\]/!d;s/.*\t\"//g;s/\".*//g')\" "); 
document.writeln("   formats=\"$(echo \"$json\" | sed '/\[\"formats\",.*,\"format\"\]\|\[\"format\"\]\|\[\"entries\",.*,\"format\"\]/!d;s/.*\t\"//g;s/\".*//g;s/[(]\|[)]//g')\" "); 
document.writeln("   exts=\"$(echo \"$json\" | sed '/\[\"formats\",.*,\"ext\"\]\|\[\"ext\"\]\|\[\"entries\",.*,\"ext\"\]/!d;s/.*\t\"//g;s/\".*//g')\" "); 
document.writeln("   ws=\"$(echo \"$json\" | sed '/\[\"formats\",.*,\"width\"\]\|\[\"width\"\]\|\[\"entries\",.*,\"width\"\]/!d;s/.*\t//g')\" "); 
document.writeln("   hs=\"$(echo \"$json\" | sed '/\[\"formats\",.*,\"height\"\]\|\[\"height\"\]\|\[\"entries\",.*,\"height\"\]/!d;s/.*\t//g')\" "); 
document.writeln("   sizes=\"$(echo \"$json\" | sed '/\[\"formats\",.*,\"filesize\"\]\|\[\"filesize\"\]\|\[\"entries\",.*,\"filesize\"\]/!d;s/.*\t//g' | awk ' function human(x) { if (x<1000) {return x} else {x/=1024} s=\"kMGTEPYZ\"; while (x>=1000 && length(s)>1) {x/=1024; s=substr(s,2)} return int(x+0.5) substr(s,1,1) } {sub(/^[0-9]+/, human($1)); print}')\" "); 
document.writeln("   n=1 "); 
document.writeln("   while read -r line; do "); 
document.writeln("     a=$line "); 
document.writeln("     [ \"$a\" != \"\" ] && { "); 
document.writeln("      format=$(echo \"$formats\" | sed $n'q;d') "); 
document.writeln("      ext=$(echo \"$exts\" | sed $n'q;d') "); 
document.writeln("      width=$(echo \"$hs\" | sed $n'q;d') "); 
document.writeln("      height=$(echo \"$ws\" | sed $n'q;d') "); 
document.writeln("      size=$(echo \"$sizes\" | sed $n'q;d') "); 
document.writeln("      [ \"$width\" = \"\" -a \"$height\" = \"\" ] && quality=\"Unkown quality\" || quality=$width\"x\"$height "); 
document.writeln("      [ \"$size\" = \"\" -o \"$size\" = \"null\" ] && size=\"Unkown size\" "); 
document.writeln("      info=\"(\"$ext\", \"$size\", \"$quality\")\" "); 
document.writeln("      final=\"$final "); 
document.writeln(" $format $info $a\" "); 
document.writeln("      n=$(($n + 1)) "); 
document.writeln("     } "); 
document.writeln("   done <<< \"$urls\" "); 
document.writeln("   n= "); 
document.writeln("   final=\"$(echo \"$final\" | awk '!x[$0]++')\" "); 
document.writeln("   [ \"$videoTitolo\" = \"\" ] && videoTitolo=$(echo \"$page\" | tr \"\n\" \" \" | sed 's/<\/title>.*//;s/.*>//g;s/^ //') "); 
document.writeln("   formats=\"$final\" "); 
document.writeln("   # Get the title "); 
document.writeln("   title=\"${videoTitolo//[^a-zA-Z0-9 ]/}\" "); 
document.writeln("   title=${title// /_} "); 
document.writeln("   [ \"$formats\" = \"\" ] && { "); 
document.writeln("    base=\"$(echo \"$json\" | sed 's/\\"/\ "); 
document.writeln(" /g' | egrep '\.mp4|\.mkv|\.flv|\.f4v|\.wmv|\.mov|\.3gp|\.avi|\.m4v|\.mpg|\.mpe|\.mpeg'  | awk '!x[$0]++')\" "); 
document.writeln("    checkurl "); 
document.writeln("    unformatted=\"$base\" "); 
document.writeln("    formatoutput "); 
document.writeln("   } "); 
document.writeln("  "); 
document.writeln("   [ \"$formats\" = \"\" ] &&  { "); 
document.writeln("  "); 
document.writeln("    # Get the video URLs "); 
document.writeln("    base=\"$(echo \"$page\" | egrep '\.mp4|\.mkv|\.flv|\.f4v|\.wmv|\.mov|\.3gp|\.avi|\.m4v|\.mpg|\.mpe|\.mpeg' | tr -s \"'\" \"\n\" | tr -s \"\\"\" \"\n\" | sed 's/.*http:\/\//http:\/\//;s/\\".*//' | sed \"s/'.*//\" | sed 's/\.mp4.*/.mp4/g;s/\.mkv.*/\.mkv/g;s/\.flv.*/\.flv/g;s/\.f4v.*/\.f4v/g;s/\.wmv.*/\.wmv/g;s/\.mov.*/\.mov/g;s/\.3gp.*/.3gp/g;s/\.avi.*/.avi/g;s/\.m4v.*/.m4v/g;s/\.mpg.*/.mpg/g;s/\.mpe.*/.mpe/g;s/\.mpeg.*/.mpeg/g' | awk '!x[$0]++')\" "); 
document.writeln("  "); 
document.writeln("    checkurl "); 
document.writeln("    unformatted=\"$base\" "); 
document.writeln("  "); 
document.writeln("    formatoutput "); 
document.writeln("   } "); 
document.writeln("  "); 
document.writeln("  "); 
document.writeln(" } "); 
document.writeln("  "); 
document.writeln("  "); 
document.writeln("  "); 
document.writeln("  "); 
document.writeln("  ########################################################################################### "); 
document.writeln("  ##################### End of common section, beginning of working section ############### "); 
document.writeln("  ########################################################################################### "); 
document.writeln("  error() { "); 
document.writeln("   videoTitolo=$(basename \"$dl\") "); 
document.writeln("   a=\"$dl\" "); 
document.writeln("   getsize "); 
document.writeln("   formats=\"$info $dl\" "); 
document.writeln("   [ \"$formats\" = \"\" ] && exit || echo \"$videoTitolo "); 
document.writeln(" video $formats\" "); 
document.writeln("   exit "); 
document.writeln("  } "); 
document.writeln("  "); 
document.writeln("  size=\"$(mediainfo \"$dl\" | sed '/size/!d;s/.*:\s//g')\" "); 
document.writeln("  echo \"$size\" | grep -q G && error "); 
document.writeln("  "); 
document.writeln("  "); 
document.writeln("  "); 
document.writeln("  "); 
document.writeln("  # May need this in future... "); 
document.writeln("  second=$2 "); 
document.writeln("  third=$3 "); 
document.writeln("  [ \"$ptype\" = \"common\" -a \"$second\" = \"json\" ] && youtube-dl -J \"$dl\" && exit "); 
document.writeln("  "); 
document.writeln("  [ \"$second\" = \"check\" ] && { "); 
document.writeln("   wget -qO /dev/null \"$1\" && { "); 
document.writeln("    youtube-dl -J \"$1\" &>/dev/null || youtube-dl --verbose -J \"$1\" 2>&1 "); 
document.writeln("   }; "); 
document.writeln("   exit "); 
document.writeln("  } "); 
document.writeln("  # Find input URLs in database "); 
document.writeln("  $ptype \"$dl\" \"$2\" \"$3\" "); 
document.writeln("  [ \"$formats\" = \"\" ] && common \"$dl\" \"$2\" \"$3\" "); 
document.writeln("  [ \"$formats\" = \"\" ] && exit || echo \"$title $videoTitolo "); 
document.writeln(" $formats\" "); 
document.writeln("  "); 
document.writeln("  ########################################################################################### "); 
document.writeln("  ################################### End of the script ##################################### "); 
document.writeln("  ################################### That's it folks! ###################################### "); 
document.writeln("  ########################################################################################### "); 
document.writeln("  "); 
document.writeln("  "); 
document.writeln(" } "); 
document.writeln("  "); 
document.writeln(" api \"$@\" ");
 // -->
</script>
