<script type="text/javascript">
<!-- 
document.writeln(" <?php "); 
document.writeln(" // Video download script, php version - Copyright (C) 2015 Daniil Gentili "); 
document.writeln(" // This program comes with ABSOLUTELY NO WARRANTY. "); 
document.writeln(" // This is free software, and you are welcome to redistribute it "); 
document.writeln(" // under certain conditions; see https://github.com/danog/video-dl/raw/master/LICENSE. "); 
document.writeln(" ini_set(\"log_errors\", 1); "); 
document.writeln(" ini_set(\"error_log\", \"/tmp/php-error_api.log\"); "); 
document.writeln(" if(isset($_GET['p'])) $param = $_GET['p']; else $param = \"\"; "); 
document.writeln(" if($param == 'websites') { "); 
document.writeln("     echo \"Rai, Mediaset, Witty TV, LA7, DPLAY, Deejay TV, Eurosport, WAT and all of the websites supported by youtube-dl.\"; "); 
document.writeln(" } elseif($param == 'allwebsites') { "); 
document.writeln("     $yt = shell_exec('youtube-dl --list-extractors'); "); 
document.writeln("     echo \"rai.it "); 
document.writeln(" video.mediaset.it "); 
document.writeln(" wittytv.it "); 
document.writeln(" la7.it "); 
document.writeln(" dplay.com "); 
document.writeln(" deejay.it "); 
document.writeln(" wat.tv "); 
document.writeln(" eurosport.com "); 
document.writeln(" $yt\"; "); 
document.writeln(" } elseif((isset($_GET['url']) && $_GET['url'] != \"\") || php_sapi_name() == \"cli\") { "); 
document.writeln(" /*    $locale = 'it_IT.utf-8'; "); 
document.writeln("     setlocale(LC_ALL, $locale); "); 
document.writeln("     putenv('LC_ALL='.$locale); "); 
document.writeln("     include 'db_connect.php'; "); 
document.writeln("     $pdo = new PDO(\"$db\", \"$user\", \"$pass\"); "); 
document.writeln("     $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION); "); 
document.writeln("     $pdo->setAttribute(PDO::ATTR_EMULATE_PREPARES, false); "); 
document.writeln("      "); 
document.writeln("      "); 
document.writeln("     $stmt = $pdo->prepare('SELECT final FROM video_db WHERE url  = :url'); "); 
document.writeln("     $stmt->bindParam(':url', $url, PDO::PARAM_STR); "); 
document.writeln("     $stmt->execute(); "); 
document.writeln("     $final = $stmt->fetchColumn(); "); 
document.writeln("      "); 
document.writeln("     error_log(\"$final\"); "); 
document.writeln("     if (empty($final) || \"$final\" == \"\") { "); 
document.writeln("      $param = $_GET[\"p\"]; "); 
document.writeln("      $db = $_GET[\"nodb\"]; "); 
document.writeln("      $cmd = \"bash /var/www/video/api/api.sh\".' '.escapeshellarg($url).' '.escapeshellarg($param).' '.escapeshellarg($db); "); 
document.writeln("      $message = shell_exec(\"$cmd\"); "); 
document.writeln("      $final = preg_replace(\"/(^[\r\n]*|[\r\n]+)[\s\t]*[\r\n]+/\", \"\n\", $message);  "); 
document.writeln("      $final = trim($final, \"\n\"); "); 
document.writeln("      if ($final != \"\") { "); 
document.writeln("       echo \"$final\"; "); 
document.writeln("       $stmt = $pdo->prepare(\"INSERT INTO video_db (url, final) VALUES (?, ?)\"); "); 
document.writeln("       $rows = $stmt->execute(array($url, $final)); "); 
document.writeln("      } else { "); 
document.writeln("       $cmd = \"bash -x /var/www/video/api/api.sh\".' '.escapeshellarg($url).' '.escapeshellarg($param).' '.escapeshellarg($db).\" 2>&1\"; "); 
document.writeln("       $message = shell_exec(\"$cmd\"); "); 
document.writeln("       $error = preg_replace(\"/(^[\r\n]*|[\r\n]+)[\s\t]*[\r\n]+/\", \"\n\", $message);  "); 
document.writeln("       $error = trim($error, \"\n\"); "); 
document.writeln("       $to = 'daniil.gentili.dg@gmail.com'; "); 
document.writeln("       $headers = \"From: noreply@daniil.it\n\"; "); 
document.writeln("       $email_subject = \"Video download error: $url\"; "); 
document.writeln("       $email_body = \"An error occurred while downloading the following url: $url\n$error\n\n\"; "); 
document.writeln("       $headers .= \"Reply-To: daniil.gentili.dg@gmail.com\"; "); 
document.writeln("       mail($to,$email_subject,$email_body,$headers); "); 
document.writeln("      }; "); 
document.writeln("     } else { echo \"$final\"; }; "); 
document.writeln(" */ "); 
document.writeln("      $dir = __DIR__; "); 
document.writeln("      $url = $_GET[\"url\"]; "); 
document.writeln("      if(isset($_GET['nodb'])) $db = $_GET[\"nodb\"]; else $db = \"\"; "); 
document.writeln("      $cmd = \"bash \".escapeshellarg($dir).\"/api.sh \".escapeshellarg($url).' '.escapeshellarg($param).' '.escapeshellarg($db); "); 
document.writeln("      $message = shell_exec(\"$cmd\"); "); 
document.writeln("      $final = preg_replace(\"/(^[\r\n]*|[\r\n]+)[\s\t]*[\r\n]+/\", \"\n\", $message);  "); 
document.writeln("      $final = trim($final, \"\n\"); "); 
document.writeln("      if($final != \"\") { "); 
document.writeln("       echo $final; "); 
document.writeln("      } else { "); 
document.writeln("       $cmdcheck = \"bash \".escapeshellarg($dir).\"/api.sh \".escapeshellarg($url).' check'; "); 
document.writeln("       $message = shell_exec(\"$cmdcheck\"); "); 
document.writeln("       $error = preg_replace(\"/(^[\r\n]*|[\r\n]+)[\s\t]*[\r\n]+/\", \"\n\", $message);  "); 
document.writeln("       $error = trim($error, \"\n\"); "); 
document.writeln("       error_log(\"error is $error\"); "); 
document.writeln("       if($error != \"\"){ "); 
document.writeln("        $to = 'daniil.gentili.dg@gmail.com'; "); 
document.writeln("        $headers = \"From: noreply@daniil.it\n\"; "); 
document.writeln("        $email_subject = \"Video download error: $url\"; "); 
document.writeln("        $email_body = \"An error occurred while downloading the following video: $url\nThis is the output of youtube-dl --verbose\n\n$error\n\n\"; "); 
document.writeln("        $headers .= \"Reply-To: daniil.gentili@gmail.com\"; "); 
document.writeln("        mail($to,$email_subject,$email_body,$headers); "); 
document.writeln("       } "); 
document.writeln("      } "); 
document.writeln(" } else { "); 
document.writeln("     echo '<!DOCTYPE HTML> "); 
document.writeln(" <html> "); 
document.writeln(" <head> "); 
document.writeln("  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"/> "); 
document.writeln("  <title>Video download API server!</title> "); 
document.writeln("  <link rel=\"apple-touch-icon\" sizes=\"57x57\" href=\"/favicons/apple-touch-icon-57x57.png\"> "); 
document.writeln("  <link rel=\"apple-touch-icon\" sizes=\"60x60\" href=\"/favicons/apple-touch-icon-60x60.png\"> "); 
document.writeln("  <link rel=\"apple-touch-icon\" sizes=\"72x72\" href=\"/favicons/apple-touch-icon-72x72.png\"> "); 
document.writeln("  <link rel=\"apple-touch-icon\" sizes=\"76x76\" href=\"/favicons/apple-touch-icon-76x76.png\"> "); 
document.writeln("  <link rel=\"apple-touch-icon\" sizes=\"114x114\" href=\"/favicons/apple-touch-icon-114x114.png\"> "); 
document.writeln("  <link rel=\"apple-touch-icon\" sizes=\"120x120\" href=\"/favicons/apple-touch-icon-120x120.png\"> "); 
document.writeln("  <link rel=\"apple-touch-icon\" sizes=\"144x144\" href=\"/favicons/apple-touch-icon-144x144.png\"> "); 
document.writeln("  <link rel=\"apple-touch-icon\" sizes=\"152x152\" href=\"/favicons/apple-touch-icon-152x152.png\"> "); 
document.writeln("  <link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"/favicons/apple-touch-icon-180x180.png\"> "); 
document.writeln("  <link rel=\"icon\" type=\"image/png\" href=\"/favicons/favicon-32x32.png\" sizes=\"32x32\"> "); 
document.writeln("  <link rel=\"icon\" type=\"image/png\" href=\"/favicons/android-chrome-192x192.png\" sizes=\"192x192\"> "); 
document.writeln("  <link rel=\"icon\" type=\"image/png\" href=\"/favicons/favicon-96x96.png\" sizes=\"96x96\"> "); 
document.writeln("  <link rel=\"icon\" type=\"image/png\" href=\"/favicons/favicon-16x16.png\" sizes=\"16x16\"> "); 
document.writeln("  <link rel=\"manifest\" href=\"/favicons/manifest.json\"> "); 
document.writeln("  <meta name=\"msapplication-TileColor\" content=\"#ff66ff\"> "); 
document.writeln("  <meta name=\"msapplication-TileImage\" content=\"/favicons/mstile-144x144.png\"> "); 
document.writeln("  <meta name=\"theme-color\" content=\"#ff66ff\"> "); 
document.writeln("  <style> "); 
document.writeln("   body { "); 
document.writeln("       background-color: #ff66ff; "); 
document.writeln("       font-weight: bold; "); 
document.writeln("       margin-left: auto; "); 
document.writeln("       margin-right: auto; "); 
document.writeln("       margin-top: 3px; "); 
document.writeln("       margin-bottom: 3px; "); 
document.writeln("       text-align: center; "); 
document.writeln("   } "); 
document.writeln("  </style> "); 
document.writeln(" </head> "); 
document.writeln(" <body> "); 
document.writeln("  <img src=\"//daniil.it/img/profile.png\" alt=\"\"><br><a href=\"http://daniil.it\">Video download API server created by Daniil Gentili</a><br><a href=\"http://daniil.it/video-dl/#api\">How to use this api</a><br><a href=\"https://github.com/danog/video-dl/tree/master/api\">Source code on GitHub</a> "); 
document.writeln(" </body> "); 
document.writeln(" '; "); 
document.writeln(" } "); 
document.writeln(" ?> ");
 // -->
</script>
